"""Add categories

Revision ID: 35c67b909343
Revises: 05c3997e0c2b
Create Date: 2026-05-18 00:22:19.033926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c67b909343'
down_revision: Union[str, Sequence[str], None] = '05c3997e0c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_author_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('posts_location_id_fkey'), 'posts', type_='foreignkey')
    op.drop_constraint(op.f('posts_author_id_fkey'), 'posts', type_='foreignkey')
    op.drop_constraint(op.f('posts_category_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'posts', 'locations', ['location_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('posts_category_id_fkey'), 'posts', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('posts_author_id_fkey'), 'posts', 'users', ['author_id'], ['id'])
    op.create_foreign_key(op.f('posts_location_id_fkey'), 'posts', 'locations', ['location_id'], ['id'])
    op.drop_constraint(None, 'comments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'comments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('comments_author_id_fkey'), 'comments', 'users', ['author_id'], ['id'])
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
