"""Add comments table

Revision ID: b7d01aaf8cc4
Revises: 5dd88317f35b
Create Date: 2026-04-25 01:06:55.580849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d01aaf8cc4'
down_revision: Union[str, Sequence[str], None] = '5dd88317f35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['public.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_constraint(op.f('posts_category_id_fkey'), 'posts', type_='foreignkey')
    op.drop_constraint(op.f('posts_author_id_fkey'), 'posts', type_='foreignkey')
    op.drop_constraint(op.f('posts_location_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'locations', ['location_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('posts_location_id_fkey'), 'posts', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('posts_author_id_fkey'), 'posts', 'users', ['author_id'], ['id'])
    op.create_foreign_key(op.f('posts_category_id_fkey'), 'posts', 'categories', ['category_id'], ['id'])
    op.drop_table('comments', schema='public')
    # ### end Alembic commands ###
